declare_args() {
  mds_subsys_pkgcfg = {
    algo = true
    boot = true
    button = true
    fs = true
    fsm = true
    topic = true
  }
}

config("mds_subsys_cfg") {
  configs = [ "../:mds_cfg" ]
}

source_set("mds_subsys") {
  public_deps = [ "cpp/:mds_subsys_cpp" ]

  if (defined(mds_subsys_pkgcfg.algo) && mds_subsys_pkgcfg.algo) {
    public_deps += [ "algo/:mds_subsys_algo" ]
  }

  if (defined(mds_subsys_pkgcfg.boot) && mds_subsys_pkgcfg.boot) {
    public_deps += [ "boot/:mds_subsys_boot" ]
  }

  if (defined(mds_subsys_pkgcfg.button) && mds_subsys_pkgcfg.button) {
    public_deps += [ "button/:mds_subsys_button" ]
  }

  if (defined(mds_subsys_pkgcfg.fs) && mds_subsys_pkgcfg.fs) {
    public_deps += [ "fs/:mds_subsys_fs" ]
  }

  if (defined(mds_subsys_pkgcfg.fsm) && mds_subsys_pkgcfg.fsm) {
    public_deps += [ "fsm/:mds_subsys_fsm" ]
  }

  if (defined(mds_subsys_pkgcfg.topic) && mds_subsys_pkgcfg.topic) {
    public_deps += [ "topic/:mds_subsys_topic" ]
  }
}
