declare_args() {
  mds_subsys_boot_pkgcfg = {
    lzma = false
  }
}

if (defined(mds_subsys_boot_pkgcfg.lzma) && mds_subsys_boot_pkgcfg.lzma) {
  pkgcfgs("lzma") {
  }
}

source_set("mds_subsys_boot") {
  sources = [ "boot.c" ]

  defines = []
  configs = []

  if (defined(mds_subsys_boot_pkgcfg.lzma) && mds_subsys_boot_pkgcfg.lzma) {
    sources += [ "boot_lzma.c" ]
    defines += [ "CONFIG_MDS_BOOT_UPGRADE_WITH_LZMA=1" ]
    configs += [ ":lzma" ]
  }

  public_configs = [ "../:mds_subsys_cfg" ]
}
