declare_args() {
  # config
  mds_core_arch = ""
  mds_config_file = ""
}

config("mds_kernel_cfg") {
  include_dirs = [ "../include" ]
  defines = []

  if (defined(mds_config_file) && mds_config_file != "") {
    defines += [ "MDS_CONFIG_FILE=\"" + mds_config_file + "\"" ]
  } else if (mds_core_arch == "") {
    if (defined(target_os) && target_os != "") {
      _target_os = target_os
    } else {
      _target_os = host_os
    }

    if (_target_os == "mac") {
      defines += [
        "CONFIG_MDS_INIT_SECTION=\"rodata,init.mdsInit.\"",
        "CONFIG_MDS_LOG_FORMAT_SECTION=\"rodata,logfmt.\"",
      ]
    }

    # add other os
  }
}

static_library("mds_kernel") {
  sources = [
    "log.c",
    "object.c",
  ]

  if (mds_core_arch != "") {
    sources += []
  }

  public_configs = [ ":mds_kernel_cfg" ]
}
