declare_args() {
  mds_kernel_pkgcfg = {
    confile = ""
    archcore = ""
    nosys = false
  }
}

config("mds_kernel_cfg") {
  include_dirs = [ "../include/kernel" ]
  defines = []

  if (defined(mds_kernel_pkgcfg.confile) && mds_kernel_pkgcfg.confile != "") {
    defines += [ "MDS_CONFIG_FILE=\"" + mds_kernel_pkgcfg.confile + "\"" ]
  }

  if (defined(target_os) && target_os != "") {
    _target_os = target_os
  } else {
    _target_os = host_os
  }

  if (_target_os == "mac") {
    defines += [
      "CONFIG_MDS_INIT_SECTION=\"rodata,init.mdsInit.\"",
      "CONFIG_MDS_LOG_FORMAT_SECTION=\"rodata,logfmt.\"",
    ]
  }
}

source_set("mds_kernel") {
  sources = [
    "critical.c",
    "device.c",
    "log.c",
    "lpc.c",
    "object.c",
    "utils.c",
  ]

  defines = []

  if (mds_kernel_pkgcfg.archcore != "") {
    sources += [ "arch/" + mds_kernel_pkgcfg.archcore + ".c" ]
  }

  if (mds_kernel_pkgcfg.nosys) {
    sources += [ "nosys.c" ]
    defines += [ "CONFIG_MDS_KERNEL_THREAD_PRIORITY_MAX=0" ]
  } else {
    sources += [
      "sys/clock.c",
      "sys/idle.c",
      "sys/ipc/condition.c",
      "sys/ipc/event.c",
      "sys/ipc/mempool.c",
      "sys/ipc/msgqueue.c",
      "sys/ipc/mutex.c",
      "sys/ipc/rwlock.c",
      "sys/ipc/semaphore.c",
      "sys/kernel.c",
      "sys/scheduler.c",
      "sys/thread.c",
      "sys/timer.c",
      "sys/workq.c",
    ]
  }

  sources += [
    "mm/heap.c",
    "mm/llff.c",
  ]

  public_configs = [ ":mds_kernel_cfg" ]
}
