declare_args() {
  mds_component_pkgcfg = {
    algo = true
    boot = false
    button = false
    fs = false
    fsm = false
    topic = false
  }
}

config("mds_component_cfg") {
  include_dirs = [
    "../include/kernel",
    "../include/device",
    "../include/components",
  ]
}

source_set("mds_components") {
  public_deps = [ "cpp/:mds_component_cpp" ]

  if (defined(mds_component_pkgcfg.algo) && mds_component_pkgcfg.algo) {
    public_deps += [ "algo/:mds_component_algo" ]
  }

  if (defined(mds_component_pkgcfg.boot) && mds_component_pkgcfg.boot) {
    public_deps += [ "boot/:mds_component_boot" ]
  }

  if (defined(mds_component_pkgcfg.button) && mds_component_pkgcfg.button) {
    public_deps += [ "button/:mds_component_button" ]
  }

  if (defined(mds_component_pkgcfg.fs) && mds_component_pkgcfg.fs) {
    public_deps += [ "fs/:mds_component_fs" ]
  }

  if (defined(mds_component_pkgcfg.fsm) && mds_component_pkgcfg.fsm) {
    public_deps += [ "fsm/:mds_component_fsm" ]
  }

  if (defined(mds_component_pkgcfg.topic) && mds_component_pkgcfg.topic) {
    public_deps += [ "topic/:mds_component_topic" ]
  }
}
