declare_args() {
  mds_component_boot_pkgcfg = {
    lzma = false
  }
}

if (defined(mds_component_boot_pkgcfg.lzma) && mds_component_boot_pkgcfg.lzma) {
  pkggroup("lzma") {
  }
}

source_set("mds_components_boot") {
  sources = [ "mds_boot.c" ]

  defines = []
  deps = []

  if (defined(mds_component_boot_pkgcfg.lzma) &&
      mds_component_boot_pkgcfg.lzma) {
    sources += [ "boot_lzma.c" ]
    defines += [ "CONFIG_MDS_BOOT_UPGRADE_WITH_LZMA=1" ]
    deps += [ ":lzma_sdk" ]
  }

  public_configs = [ "../:mds_component_cfg" ]
}
