declare_args() {
  mds_component_fs_pkgcfg = {
    littlefs = false
  }
}

source_set("mds_components_fs") {
  sources = [ "mds_fs.c" ]

  defines = []
  deps = []

  if (defined(mds_component_fs_pkgcfg.littlefs) &&
      mds_component_fs_pkgcfg.littlefs) {
    deps += [ "littlefs/:fs_littlefs" ]
  }

  public_configs = [ "../:mds_component_cfg" ]
}
